### ISSUE TITLE
トークン認証メソッドのパラメータ変更

### ISSUE THREAD

**Issue by KenTanaka** [EC-CUBE/TwoFactorAuthCustomerApp42#14]
・安全性を高めるため、デフォルト値の1に変更する事。

`$this->tfa->verifyCode($authKey, $token, 2);`
↓
`$this->tfa->verifyCode($authKey, $token, 1);`

**Comment by sai-gillingham** [comment]
@KenTanaka

Issueを上げて頂いてありがとうございます。

verifyCodeの第３パラメータを1に変更しましたので、ご確認お願いいたします。

https://github.com/EC-CUBE/TwoFactorAuthCustomerApp42/pull/15
